### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by stnbu** [jakobhellermann/wasm-server-runner#10]
Following the instructions on the README, I attempted to run/serve [this](https://github.com/stnbu/bevy_play/tree/13f41fe977ed772ea2f79b9694bd8c23c2f2a515) project.

When I do, it fails to run with the following message:

```
$ cargo run --target wasm32-unknown-unknown
warning: unused manifest key: target.wasm32-unknown-unknown.runner
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/wasm32-unknown-unknown/debug/bevy_play.wasm`
target/wasm32-unknown-unknown/debug/bevy_play.wasm: target/wasm32-unknown-unknown/debug/bevy_play.wasm: cannot execute binary file
```

I get the same behavior even if I remove `Cargo.lock` and `target/`.

The file is executable in the unix sense:

```
$ ls -l target/wasm32-unknown-unknown/debug/bevy_play.wasm
-rwxr-xr-x 1 mburr staff 341363957 Jun 24 11:03 target/wasm32-unknown-unknown/debug/bevy_play.wasm
```

Other:

```
$ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/mburr/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin
1.52.1-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

thumbv7m-none-eabi
wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)
```

**Comment by stnbu** [comment]
I meant the `cannot execute binary file` part. It prints that and exits. It never serves the file at all.

**Comment by stnbu** [comment]
Ooooh! Yeesh. 🤦🤦🤦

Ok, I comprehend now and I didn't read your first response carefully..._enough_. ;-)

It now works as expected of course! Thanks for your help/patience!

**Comment by kholbekj** [comment]
What tripped me up reading this was 
>You get the warning because the target.<target>.runner key isn't part of your application's Cargo.toml

I thought you mean the warning is signifying that the key isn't present in my application's Cargo.toml - which it is.

What I realize you meant was, target.<target>.runner key is not *supposed* to be part of your application's Cargo.toml

Now I can proceed :D
